/* Copyright uJL 2019. */

var conection = true;
var mostrarAlertas = false;
var contentPath = "contenido/";
var mobileCurse = false;
var navegationBlock = false;
var hayEvaluacion = false;
var minimoAprobatorio = 80;
var haySubtitulos = false;
var conIntentos = false;
var maxIntentos = 2;
var intento = 0;
var sourceHeigth = 648;
var sourceWidth = 1152;
var posTopPantalla = 0;
var posBottomPantalla = 0;
var altoPantalla = 648;
var pantallaCompleta = false;

/* Pantallas del curso */
var course = new Object();
course.pages = [
    { title: "Pantalla", url: "SAP_Nomina_Manager_01.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_02.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_03.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_04.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_05.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_06.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_07.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_08.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_09.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_10.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_11.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_12.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_13.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_14.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_15.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_16.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_17.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_18.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_19.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_20.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_21.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_22.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_23.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_24.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_25.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_26.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_27.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_28.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_29.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_30.html", navegacion: true, menu: true },  
    { title: "Pantalla", url: "SAP_Nomina_Manager_31.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_32.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_33.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_34.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_35.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_36.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_37.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_38.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_39.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_40.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_41.html", navegacion: true, menu: true },
    { title: "Pantalla", url: "SAP_Nomina_Manager_42.html", navegacion: true, menu: true }
];

/* Pantallas de recursos */
var recursos = new Object();
recursos.pages = [
    { title: "Índice", url: "indice.html", navegacion: true, menu: true },
    { title: "Ayuda", url: "ayuda.html", navegacion: true, menu: true }
];

/* Audios del curso */
var grupoAudios = new buzz.group([
    /*0*/ new buzz.sound("contenido/audios/audio0", { formats: ["mp3"], preload: true }),
    /*1*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_01_01", { formats: ["mp3"], preload: true }),
    /*2*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_02_01", { formats: ["mp3"], preload: true }),
    /*3*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_03_01", { formats: ["mp3"], preload: true }),
    /*4*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_04_01", { formats: ["mp3"], preload: true }),
    /*5*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_05_01", { formats: ["mp3"], preload: true }),
    /*6*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_06_01", { formats: ["mp3"], preload: true }),
    /*7*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_06_02", { formats: ["mp3"], preload: true }),
    /*8*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_07_01", { formats: ["mp3"], preload: true }),
    /*9*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_07_02", { formats: ["mp3"], preload: true }),
    /*10*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_07_03", { formats: ["mp3"], preload: true }),
    /*11*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_08_01", { formats: ["mp3"], preload: true }),
    /*12*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_08_02", { formats: ["mp3"], preload: true }),
    /*13*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_09_01", { formats: ["mp3"], preload: true }),
    /*14*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_09_02", { formats: ["mp3"], preload: true }),
    /*15*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_10_01", { formats: ["mp3"], preload: true }),
    /*16*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_11_01", { formats: ["mp3"], preload: true }),
    /*17*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_12_01", { formats: ["mp3"], preload: true }),
    /*18*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_13_01", { formats: ["mp3"], preload: true }),
    /*19*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_14_01", { formats: ["mp3"], preload: true }),
    /*20*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_14_02", { formats: ["mp3"], preload: true }),
    /*21*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_14_03", { formats: ["mp3"], preload: true }),
    /*22*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_14_04", { formats: ["mp3"], preload: true }),
    /*23*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_14_05", { formats: ["mp3"], preload: true }),
    /*24*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_14_06", { formats: ["mp3"], preload: true }),
    /*25*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_14_07", { formats: ["mp3"], preload: true }),
    /*26*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_14_08", { formats: ["mp3"], preload: true }),
    /*27*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_15_01", { formats: ["mp3"], preload: true }),
    /*28*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_15_02", { formats: ["mp3"], preload: true }),
    /*29*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_16_01", { formats: ["mp3"], preload: true }),
    /*30*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_17_01", { formats: ["mp3"], preload: true }),
    /*31*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_18_01", { formats: ["mp3"], preload: true }),
    /*32*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_19_01", { formats: ["mp3"], preload: true }),
    /*33*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_20_01", { formats: ["mp3"], preload: true }),
    /*34*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_20_02", { formats: ["mp3"], preload: true }),
    /*35*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_20_03", { formats: ["mp3"], preload: true }),
    /*36*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_20_04", { formats: ["mp3"], preload: true }),
    /*37*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_20_05", { formats: ["mp3"], preload: true }),
    /*38*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_20_06", { formats: ["mp3"], preload: true }),
    /*39*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_01", { formats: ["mp3"], preload: true }),
    /*40*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_02", { formats: ["mp3"], preload: true }),
    /*41*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_03", { formats: ["mp3"], preload: true }),
    /*42*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_04", { formats: ["mp3"], preload: true }),
    /*43*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_05", { formats: ["mp3"], preload: true }),
    /*44*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_06", { formats: ["mp3"], preload: true }),
    /*45*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_07", { formats: ["mp3"], preload: true }),
    /*46*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_08", { formats: ["mp3"], preload: true }),
    /*47*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_09", { formats: ["mp3"], preload: true }),
    /*48*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_10", { formats: ["mp3"], preload: true }),
    /*49*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_11", { formats: ["mp3"], preload: true }),
    /*50*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_12", { formats: ["mp3"], preload: true }),
    /*51*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_13", { formats: ["mp3"], preload: true }),
    /*52*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_14", { formats: ["mp3"], preload: true }),
    /*53*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_15", { formats: ["mp3"], preload: true }),
    /*54*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_16", { formats: ["mp3"], preload: true }),
    /*55*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_17", { formats: ["mp3"], preload: true }),
    /*56*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_18", { formats: ["mp3"], preload: true }),
    /*57*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_19", { formats: ["mp3"], preload: true }),
    /*58*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_20", { formats: ["mp3"], preload: true }),
    /*59*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_21_21", { formats: ["mp3"], preload: true }),
    /*60*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_22_01", { formats: ["mp3"], preload: true }),
    /*61*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_22_02", { formats: ["mp3"], preload: true }),
    /*62*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_23_01", { formats: ["mp3"], preload: true }),
    /*63*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_24_01", { formats: ["mp3"], preload: true }),
    /*64*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_25_01", { formats: ["mp3"], preload: true }),
    /*65*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_25_02", { formats: ["mp3"], preload: true }),
    /*66*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_25_03", { formats: ["mp3"], preload: true }),
    /*67*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_01", { formats: ["mp3"], preload: true }),
    /*68*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_02", { formats: ["mp3"], preload: true }),
    /*69*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_03", { formats: ["mp3"], preload: true }),
    /*70*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_04", { formats: ["mp3"], preload: true }),
    /*71*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_05", { formats: ["mp3"], preload: true }),
    /*72*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_06", { formats: ["mp3"], preload: true }),
    /*73*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_07", { formats: ["mp3"], preload: true }),
    /*74*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_08", { formats: ["mp3"], preload: true }),
    /*75*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_09", { formats: ["mp3"], preload: true }),
    /*76*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_10", { formats: ["mp3"], preload: true }),
    /*77*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_11", { formats: ["mp3"], preload: true }),
    /*78*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_12", { formats: ["mp3"], preload: true }),
    /*79*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_13", { formats: ["mp3"], preload: true }),
    /*80*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_14", { formats: ["mp3"], preload: true }),
    /*81*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_15", { formats: ["mp3"], preload: true }),
    /*82*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_16", { formats: ["mp3"], preload: true }),
    /*83*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_17", { formats: ["mp3"], preload: true }),
    /*84*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_18", { formats: ["mp3"], preload: true }),
    /*85*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_19", { formats: ["mp3"], preload: true }),
    /*86*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_20", { formats: ["mp3"], preload: true }),
    /*87*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_21", { formats: ["mp3"], preload: true }),
    /*88*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_22", { formats: ["mp3"], preload: true }),
    /*89*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_23", { formats: ["mp3"], preload: true }),
    /*90*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_24", { formats: ["mp3"], preload: true }),
    /*91*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_25", { formats: ["mp3"], preload: true }),
    /*92*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_26", { formats: ["mp3"], preload: true }),
    /*93*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_27", { formats: ["mp3"], preload: true }),
    /*94*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_28", { formats: ["mp3"], preload: true }),
    /*95*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_29", { formats: ["mp3"], preload: true }),
    /*96*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_30", { formats: ["mp3"], preload: true }),
    /*97*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_31", { formats: ["mp3"], preload: true }),
    /*98*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_32", { formats: ["mp3"], preload: true }),
    /*99*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_33", { formats: ["mp3"], preload: true }),
    /*100*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_34", { formats: ["mp3"], preload: true }),
    /*101*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_35", { formats: ["mp3"], preload: true }),
    /*102*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_36", { formats: ["mp3"], preload: true }),
    /*103*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_37", { formats: ["mp3"], preload: true }),
    /*104*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_26_38", { formats: ["mp3"], preload: true }),
    /*105*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_27_01", { formats: ["mp3"], preload: true }),
    /*106*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_28_01", { formats: ["mp3"], preload: true }),
    /*107*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_28_02", { formats: ["mp3"], preload: true }),
    /*108*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_29_01", { formats: ["mp3"], preload: true }),
    /*109*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_01", { formats: ["mp3"], preload: true }),
    /*110*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_02", { formats: ["mp3"], preload: true }),
    /*111*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_03", { formats: ["mp3"], preload: true }),
    /*112*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_04", { formats: ["mp3"], preload: true }),
    /*113*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_05", { formats: ["mp3"], preload: true }),
    /*114*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_06", { formats: ["mp3"], preload: true }),
    /*115*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_07", { formats: ["mp3"], preload: true }),
    /*116*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_08", { formats: ["mp3"], preload: true }),
    /*117*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_09", { formats: ["mp3"], preload: true }),
    /*118*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_10", { formats: ["mp3"], preload: true }),
    /*119*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_11", { formats: ["mp3"], preload: true }),
    /*120*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_12", { formats: ["mp3"], preload: true }),
    /*121*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_13", { formats: ["mp3"], preload: true }),
    /*122*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_14", { formats: ["mp3"], preload: true }),
    /*123*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_15", { formats: ["mp3"], preload: true }),
    /*124*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_16", { formats: ["mp3"], preload: true }),
    /*125*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_17", { formats: ["mp3"], preload: true }),
    /*126*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_18", { formats: ["mp3"], preload: true }),
    /*127*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_19", { formats: ["mp3"], preload: true }),
    /*128*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_20", { formats: ["mp3"], preload: true }),
    /*129*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_21", { formats: ["mp3"], preload: true }),
    /*130*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_22", { formats: ["mp3"], preload: true }),
    /*131*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_23", { formats: ["mp3"], preload: true }),
    /*132*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_24", { formats: ["mp3"], preload: true }),
    /*133*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_25", { formats: ["mp3"], preload: true }),
    /*134*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_26", { formats: ["mp3"], preload: true }),
    /*135*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_30_27", { formats: ["mp3"], preload: true }),
    /*136*/ new buzz.sound("contenido/audios/SAP_Nomina_Manager_31_01", { formats: ["mp3"], preload: true }),
]);
